### ISSUE TITLE
Lithium incompatibility

### ISSUE THREAD

**Issue by WarpedWartWars** [WarpedWartWars/instant_pistons#1]
error:
```
[08:54:03] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: offset must be one of {0f, 0.5f, 1f}
	at net.minecraft.class_265.getIndexForOffsetSimplifiedShapes(class_265.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_265.setShape(class_265.java:1017) ~[client-intermediary.jar:?]
	at net.minecraft.class_2669.getOffsetAndSimplified(class_2669.java:1086) ~[client-intermediary.jar:?]
	at net.minecraft.class_2669.handler$boo000$lithium$skipVoxelShapeUnion(class_2669.java:1060) ~[client-intermediary.jar:?]
	at net.minecraft.class_2669.method_11512(class_2669.java:386) ~[client-intermediary.jar:?]
	at net.minecraft.class_2667.method_9549(class_2667.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java:1129) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:1125) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_37403(class_4970.java:411) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:1346) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_2943(class_638.java:405) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_2941(class_638.java:361) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2052) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```
G4mespeed disables Lithium's `PistonBlockEntity` (`class_2669`) mixin, thus making `handler$boo000$lithium$skipVoxelShapeUnion` not exist

**Comment by WarpedWartWars** [comment]
also for reference, `class_265` is `VoxelShape`
